services:
  db:
    image: mysql:8.0
    container_name: database
    ports:
      - "3307:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/init_db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crawl
    networks:
      - app_network
    restart: always

  db_api:
    build: 
      context: ./db_api
      dockerfile: Dockerfile
    container_name: db_api
    ports:
      - "9000:8000"
    depends_on:
      - db
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
